id: PB844BABB
initial_creation_type: input
source_metadata:
  title: Namkha Drimed Rinpoche Series
  language: en
  description: 'Texts by and about Namkha Drimed Rabjam Rinpoche (nam mkha'' dri med
    rab ''byams rin po che, b. 1938), the modern tertön renowned for his connection
    with King Gesar:'
  volume:
    08bb0621f49a4d9d8c0ec2798541f21b:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T00:58:29.391899'
last_modified_at: '2022-03-01T00:58:29.391905'
